
//----------------
//
// This file is autogenerated
//
//----------------
namespace TextTemplateAttempt.Version
{
	static class VersionInfo
	{
		public const int MajorVersion = 8;
		public const int MinorVersion = 1;
	}
}